---
title: "Dashboard!!"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(p8105.datasets)

library(plotly)

data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |>
  mutate(rating = review_scores_location / 2) |>
  select(
    rating, neighbourhood_group, neighbourhood, room_type, lat, long, price) |>
  drop_na(rating) |>
  filter(
    neighbourhood_group == "Manhattan", 
    room_type == "Entire home/apt", 
    price %in% 100:500
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_airbnb |>
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: ", price, 
                            "\nNeighborhood: ", neighbourhood)) |>
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label, 
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

### Chart C

```{r}
nyc_airbnb |>
  count(neighbourhood) |>
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |>
  plot_ly(
    x = ~neighbourhood, y = ~n, 
    type = "bar"
  )
```

