---
title: "NY Weather Plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill

---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)

data("ny_noaa")

my_ny_df = 
  ny_noaa |>
  mutate(
    tmax = as.integer(tmax), 
    tmin = as.integer(tmin), 
    tmax = tmax/10, 
    tmin = tmin/10, 
    prcp = prcp/10
  ) |>
  drop_na() |>
  mutate(
    year = year(date), 
    month = month(date))
```


{data-width=650}
-----------------------------------------------------------------------

### Chart A


```{r}
my_ny_df |>
  filter(id == "USC00301110", 
         snow > 1) |>
  mutate(text_label = str_c("Date: ", date, 
                            "\nMinimum Temperature: ", tmin,
                            "\nMaximum Temperature: ", tmax)) |>
  plot_ly(
    x = ~snow, y = ~snwd, text = ~text_label, 
    type = "scatter", mode = "markers", color = ~year
  ) |>
  layout(
    xaxis = list(title = "Snowfall in Camden, NY (mm)"),
    yaxis = list(title = "Snow depth in Camden, NY (mm)"))
  
```


{data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
my_ny_df |>
  filter(snow > 250) |>
  count(id) |>
  mutate(id = fct_reorder(id, n)) |>
  plot_ly(
    x = ~id, y = ~n, type = "bar"
  ) |>
  layout(
    xaxis = list(title = "ID"),
    yaxis = list(title = "Number of Days with snowfall > 250 mm"))
```


### Chart C


```{r}
my_ny_df |>
  mutate(
    year = year(date), 
    month = month(date)) |>
  filter(
    id == "USW00094789") |>
  plot_ly(
    x = ~month, y = ~tmax, type = "box", colors = "viridis"
  ) |>
  layout(
    xaxis = list(title = "Month"),
    yaxis = list(title = "Max. Temp. of the JFK Airport (C)"))
```
